# fly.toml generated for La Menace Telegram Bot
# Replace "la-menace-bot" with your app name: fly launch --name la-menace-bot
app = "la-menace-bot"
primary_region = "cdg"

[build]
  dockerfile = "Dockerfile"

[env]
  # Keepalive tiny HTTP server
  KEEPALIVE = "1"
  PORT = "8080"

# Mount a volume to persist bot_state.pickle
[mounts]
  source="bot_data"
  destination="/data"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "requests"
    soft_limit = 20
    hard_limit = 25

  [[http_service.http_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
    method = "GET"
    path = "/"
    protocol = "http"
    tls_skip_verify = false
